### ISSUE TITLE
An error need help

### ISSUE THREAD

**Issue by smallduan** [NikolausKurcz/mem4py_adapter#1]
Hi

Thank you for upload this tutorial, I have tried to run it on my desktop but meet an error as bellow:
![微信截图_20230619161018](https://github.com/NikolausKurcz/mem4py_adapter/assets/52167150/50c1fc6c-0523-4449-8c2a-2591b20d6347)
I have installed the mem4py and use openfoamv2212 to run the tutorial. Is it because my mem4py installation didn't work?

Best regards

**Comment by NikolausKurcz** [comment]
Hi!For me it looks like you did not install mem4py from the testing branch. ?Could you check this, I made some small modifications to the original mem4py code to be able to run the example. Let me know how it goes. Cheers,NikiOn 19. Jun 2023, at 10:16, smallduan ***@***.***> wrote:﻿
Hi
Thank you for upload this tutorial, I have tried to run it on my desktop but meet an error as bellow:

I have installed the mem4py and use openfoamv2212 to run the tutorial. Is it because my mem4py installation didn't work?
Best regards

**Comment by smallduan** [comment]
Hi @NikolausKurcz 

Thank you, I have tried the [https://github.com/NikolausKurcz/mem4py], and meet the same error. I read the code in the **mem4py.pyx** file and  don't find uDot in the Men4py class. I am not sure if this branch is what you are talking about. Can you give me a link to the testing branch?

Best regards

**Comment by NikolausKurcz** [comment]
Hi,Sure, can you try this link?NikolausKurcz/mem4py at testinggithub.comOne of the changes is that I am cashing a lot of variables to be able to restart the simulation (not sure which of them are really needed) On 20. Jun 2023, at 04:05, smallduan ***@***.***> wrote:﻿
Hi @NikolausKurcz
Thank you, I have tried the [https://github.com/NikolausKurcz/mem4py], and meet the same error. I read the code in the mem4py.pyx file and  don't find uDot in the Men4py class. I am not sure if this branch is what you are talking about. Can you give me a link to the testing branch?
Best regards

**Comment by smallduan** [comment]
Hi @NikolausKurcz 

I am sory, I can't find the testinggithub.com, Could you please upload your modified mem4py under the mem4py_adapter project?

Best regards

**Comment by NikolausKurcz** [comment]
oh sorry please try this link: 

https://github.com/NikolausKurcz/mem4py/tree/testing

**Comment by smallduan** [comment]
Hi @NikolausKurcz 
Many thanks for your kind and warm help. The new mem4py given by your link works.


Best regards
